### ISSUE TITLE
Having trouble with nREPL

### ISSUE THREAD

**Issue by scttnlsn** [tomjakubowski/weasel#27]
I'm trying to get a browser connected REPL setup with nREPL, Piggieback and Weasel.  I start up a `lein repl` and evaluate the following:

```clojure
(require 'weasel.repl.websocket)
(cemerick.piggieback/cljs-repl
        :repl-env (weasel.repl.websocket/repl-env
                   :ip "0.0.0.0" :port 9001))
```

I then load my ClojureScript application in the browser and it successfully opens the websocket connection by calling:

```clojure
(ws-repl/connect "ws://localhost:9001")
```

This all works great.  I can evaluate code directly in the REPL and have it run in the browser.  For example, entering the following in the REPL successfully displays an alert dialog in the browser:

```clojure
(js/alert)
```

The problem I'm encountering is when I try to evaluate the same thing over an nREPL connection (i.e. from an editor).  In that case I get the error:

`CompilerException java.lang.RuntimeException: No such namespace: js`

To demonstrate the issue I can open a separate `lein repl` and create an nREPL connection:

```clojure
(use '[clojure.tools.nrepl.repl])
(def conn (repl/connect :port 58569))
(def client (repl/client conn 10000))
(repl/message client {:op "eval" :code "(js/alert)"})
``` 

I get the following response:

```
({:ex "class clojure.lang.Compiler$CompilerException", :id "83ce9217-016a-4cd2-b652-9dfce01a3dcf", :root-ex "class clojure.lang.Compiler$CompilerException", :session "07f7d6cf-7ee6-4a59-b99e-4e1fcd134e33", :status ["eval-error"]} {:err "CompilerException java.lang.RuntimeException: No such namespace: js, compiling:(/private/var/folders/z3/x8fdxj9x1rv8zt4ylnkjcgyh0000gn/T/form-init2789710204217740010.clj:1:1) \n", :id "83ce9217-016a-4cd2-b652-9dfce01a3dcf", :session "07f7d6cf-7ee6-4a59-b99e-4e1fcd134e33"} {:id "83ce9217-016a-4cd2-b652-9dfce01a3dcf", :session "07f7d6cf-7ee6-4a59-b99e-4e1fcd134e33", :status ["done"]})
```

Is this related to Weasel?  Is there any additional configuration I need to do?  I'm not very familiar with CIDER/Emacs but, strangely, this error does not occur with that setup.  It does happen when I use the nREPL integration in Sublime Text 2 or Atom or when making nREPL calls directly as illustrated above.

Any help you can provide with this would be greatly appreciated.  Let me know if there's any additional information I can provide to make this more clear.

**Comment by tomjakubowski** [comment]
The Clojure nREPL client error looks like it's still running a Clojure REPL, probably because you did not appear to piggieback that session.

I don't think there's anything actionable here; if you disagree feel free to comment here and I'll reconsider. Thanks for the report!
