### ISSUE TITLE
Update to new REPL APIs

### ISSUE THREAD

**Issue by mfikes** [tomjakubowski/weasel#37]
[Changes are being made](https://github.com/clojure/clojurescript/wiki/Custom-REPLs) to `cljs.repl` that will require updates to derivative REPLs.

David Nolen [indicated](http://logs.lazybot.org/irc.freenode.net/%23clojurescript/2014-12-29.txt) that he wants to allow time to allow REPLs to update before the code in the latest ClojureScript tree is landed as a release.

I suspect one consequence is that the `(in-ns ...)` form produces an arity exception if tried with the latest ClojureScript tree.

(Note: It is not at all clear to me whether anything needs to be done in Weasel. It could be that all of the needed changes are lower down in the stack.)

**Comment by mfikes** [comment]
The updates to the REPL apis are now available in ClojureScript 0.0-2644.

**Comment by mfikes** [comment]
Note that if you try using the updates in my experimental fork, you will encounter an error about *print-fn*. I thought this was just something that needs to be addressed in the fork, but now think it may be a ClojureScript defect [CLJS-956](http://dev.clojure.org/jira/browse/CLJS-956).

**Comment by the-kenny** [comment]
@mfikes do you know if this also fixes the issue with ```in-ns``` from https://github.com/tomjakubowski/weasel/issues/26 ?

**Comment by mfikes** [comment]
@the-kenny No and yes. I suspect that #26 could easily become obsolete with the new REPL APIs, simply because there is some new explicit support for `in-ns` and other REPL "special forms", and some changes are needed to support `in-ns`.

Prior to 0.0-2644, I wasn't experiencing #26 (I am using Cursive, so perhaps there is enough difference there).

But, regardless, with the new REPL APIs, I get a fundamental ArityException when invoking `in-ns`. In my [experimental fork](https://github.com/mfikes/weasel) to try to understand the needed Weasel changes, I haven't sorted out what the root cause of this is. Perhaps it is in piggyback, and will also affect Austin... don't know yet.

**Comment by the-kenny** [comment]
#26 isn't really about ```in-ns``` directly: Calling it from the REPL itself worked fine. The problem was in the nrepl-protocol.

**Comment by mfikes** [comment]
Here is the `ArityException` I get for `in-ns`:

```
(in-ns 'foo.bar)
ArityException Wrong number of args (2) passed to: repl/fn--4253/self--4259  clojure.lang.AFn.throwArity (AFn.java:429)
```

**Comment by mfikes** [comment]
There is an interesting design issue to sort out: The Node.js REPL bootstraps by loading `cljs.core` into an initially empty Node.js environment, and all loading is accomplished by directly loading JavaScript source from the filesystem via an override to `CLOSURE_IMPORT_SCRIPT`.

It is not clear to me how this should end up working for Weasel, which has a Weasel client connect to the Weasel server, where the client already has `cljs.core` loaded along with at least enough JavaScript to support the `(ws-repl/connect "ws://localhost:9001")` call. (This concept was discussed with David Nolan a bit in the IRC log copied into the previous comment.)

It seems like two drastically different approaches could be taken:
1. Make radical changes to have some minimal bootstrap JavaScript start listening on a WebSocket, and have the Weasel REPL load in things just like the Node.js REPL does.
2. Continue to have the client call `ws-repl/connect`, and make assumptions in the Weasel server that the client already has certain libs pre-loaded.

The first approach would appear to result in closer tracking between the compiled state and what is actually running in the JavaScript environment, but it seems like it presents a lot of other challenges.

In any case, another challenge is that, unlike in the Node.js REPL, Weasel doesn't know the details of the target JavaScript execution environment, perhaps making it challenging to write a proper override to `CLOSURE_IMPORT_SCRIPT`. (One thing to consider: when targeting mobile JavaScript engines, the target environment likely doesn't have filesystem access to the compilation output directory, and `CLOSURE_IMPORT_SCRIPT` would have to load files perhaps via the Weasel TCP connection.)

My experimental fork currently has code in it that mimic's the Node.js REPL in some respects, but it hasn't addressed `CLOSURE_IMPORT_SCRIPT` and arguably currently behaves a lot like the currently-released Weasel implementation.

**Comment by mfikes** [comment]
Much of what I described in the previous comment is probably answered by studying the way the [new browser REPL](https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/repl/browser.clj) operates with the latest ClojureScript updates.

**Comment by mfikes** [comment]
It appears that Weasel minimally needs to be updated to support the new 2-arg arity of `-setup` in `IJavaScriptEnv` that was introduced in ClojureScript `0.0-2665`. It is not clear if anything more *must* be done at this point; with this change, things work. I'm presuming that the ArityException associated with `in-ns` is lower down in the stack. I'll put together a PR addressing this.

**Comment by martinklepsch** [comment]
Probably relevant to this issue: https://github.com/cemerick/piggieback/issues/38

**Comment by mfikes** [comment]
Yes, @martinklepsch I can confirm that with the changes in cemerick/piggieback#38 my `(in-ns ...)` forms work properly.

**Comment by the-kenny** [comment]
Do just the ```(in-ns ...)``` forms work properly, or do the keyboard shortcuts in Emacs (```C-c M-n```, ```(cider-repl-set-ns NS)``` work fine too?

**Comment by mfikes** [comment]
@the-kenny I am using Cursive, with the entire stack involving [simple-brepl](https://github.com/james-henderson/simple-brepl) to start Weasel. In Cursive, both manually typing `(in-ns 'foo)` and using `Tools > REPL > Switch REPL NS to current file` menu work.

**Comment by mfikes** [comment]
This ticket can be closed IMHO, especially in light of work that will probably be done for #42

**Comment by tomjakubowski** [comment]
In particular we should ensure that we're meeting the expectations noted here: <https://github.com/clojure/clojurescript/wiki/Custom-REPLs>.

**Comment by swannodette** [comment]
wrt to c9f6b08, this is good enough for browser based contexts which is the primary use case for Weasel far as I know. If Weasel is being used for other targets then yes you may need to configure {{goog.require}} monkey patching. Seems pretty low priority and honestly better handled by making a new REPL for dramatically different targets a la [Ambly](https://github.com/omcljs/ambly).
