### ISSUE TITLE
Browser-side error trying to connect with latest CLJS

### ISSUE THREAD

**Issue by j-mckitrick** [tomjakubowski/weasel#57]
I'm running 0.0-3123.

Here's my server-side setup:

(ns pts.dev
  (:require [cemerick.piggieback :as piggieback]
            [weasel.repl.websocket :as weasel]))

(println "Loaded dev")

(defn browser-repl []
  ;;(require 'weasel.repl.websocket)
  (piggieback/cljs-repl :repl-env (weasel/repl-env :ip "0.0.0.0" :port 9001)))

on the client side:

(defn browser-repl []
  (if-not (ws-repl/alive?)
    (println "Result " (ws-repl/connect "ws://localhost:9001"))))

Here's the error I see in the Firefox console:
"Result  nil" main.js:21579:0
"goog.require could not find: cljs.core" main.js:19687:6

Error: goog.require could not find: cljs.core main.js:19689:10
TypeError: client.home is undefined home:39:5
"Opened Websocket REPL connection" main.js:75106:10
"goog.require could not find: cljs.core"

**Comment by swannodette** [comment]
FWIW I gave this a shot with piggieback installing from master and using my weasel fork https://github.com/swannodette/weasel. I could connect and do basic eval though most of the nice new stuff in 0.0-3123 doesn't seem to work.

If I drop piggieback and use `lein trampoline run -m clojure.main` to start my Weasel session, everything seems to work OK (though you'll get some innocuous errors).

**Comment by j-mckitrick** [comment]
I've installed snapshots before, but how do I install directly from your
fork?


--
Jonathon McKitrick

**Comment by martinklepsch** [comment]
@j-mckitrick you need to clone the repo and run `lein install` inside it. This will install it into your local `.m2` repository.

**Comment by tomjakubowski** [comment]
@j-mckitrick I've merged David's PR so you can do a `lein install` from a clone of this repository and get his changes.

**Comment by tomjakubowski** [comment]
(I will also cut a release soon, I promise)

**Comment by j-mckitrick** [comment]
I just tried, to no available.  I'm not sure what else to try at this
point.  Is there any other diagnostic info I can get to?


--
Jonathon McKitrick

**Comment by j-mckitrick** [comment]
To no avail*


--
Jonathon McKitrick

**Comment by swannodette** [comment]
I actually spent about 3 hours last night trying to get piggieback to work. No such luck. Without piggieback Weasel works fine. With piggieback I can start the REPL but most of the new REPL features do not work. I don't think we're going to get much progress on this without more help/input from @cemerick at this point.

**Comment by j-mckitrick** [comment]
Well, I won't try to spend much time fighting with it, then.

I assume this should all work with httpkit instead of jetty, correct?


--
Jonathon McKitrick

**Comment by cemerick** [comment]
@swannodette do you mean that you're seeing the same error? Or that you were looking for REPLs started via piggieback to behave as those provided by ClojureScript itself? That won't happen until someone reformulates nREPL support for ClojureScript REPLs using the new bits it provides.

I'll be doing it at some point, but it's not a blocker for me personally at the moment, so not a top priority.

**Comment by cemerick** [comment]
Whoops, my bad, thought I was commenting on cemerick/piggieback#48. :-P

**Comment by swannodette** [comment]
@cemerick sorry, not the same error. In order to avoid @j-mckitrick's specific problem all that needs to happen is that piggieback needs to supply the `:output-dir` REPL option. I can push my various fixes to my fork tomorrow. I think with some further guidance from you we can make piggieback work reasonably well until something better lands. I don't use piggieback or weasel, but I'd be happy to see people have a near term solution for Cider, Cursive, etc. with more recent versions of ClojureScript.

**Comment by j-mckitrick** [comment]
David, how do you develop with clojurescript then? I mean, the REPL is fine
for exploring and debugging etc, but what about actually editing and
navigating source code?

On Wednesday, March 18, 2015, David Nolen <notifications@github.com> wrote:

> @cemerick <https://github.com/cemerick> sorry, not the same error. In
> order to avoid @j-mckitrick <https://github.com/j-mckitrick>'s specific
> problem all that needs to happen is that piggieback needs to supply the
> :output-dir REPL option. I can push my various fixes to my fork tomorrow.
> I think with some further guidance from you we can make piggieback work
> reasonably well until something better lands. I don't use piggieback or
> weasel, but I'd be happy to see people have a near term solution for Cider,
> Cursive, etc. with more recent versions of ClojureScript.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomjakubowski/weasel/issues/57#issuecomment-83244928>.
>


-- 

--
Jonathon McKitrick

**Comment by j-mckitrick** [comment]
@cemerick @tomjakubowski Weasel and piggieback should work with httpkit, not just jetty, correct?

**Comment by tomjakubowski** [comment]
@j-mckitrick Weasel should work with httpkit, modulo horrifying version mismatch bugs because Weasel itself uses httpkit for the WebSocket server.

**Comment by j-mckitrick** [comment]
@tomjakubowski Here's what I'm seeing now, with piggieback 0.2.0 and weasel 0.6.0:

mckitrick@jmckitrick-mbp.local ~/Code/pts % rlwrap lein trampoline run -m clojure.main                                                                                                                                                         feature/weasel-repl ?  16:36:05
Clojure 1.6.0
user=> (require 'weasel.repl.websocket)
nil
user=> (cemerick.piggieback/cljs-repl :repl-env (weasel.repl.websocket/repl-env :ip "0.0.0.0" :port 9001))
IllegalArgumentException No value supplied for key: weasel.repl.websocket.WebsocketEnv@49ac47e0  clojure.lang.PersistentHashMap.create (PersistentHashMap.java:77)
user=>

**Comment by cemerick** [comment]
@j-mckitrick Drop the `:repl-env`. And, trampoline likely will not work.

**Comment by j-mckitrick** [comment]
I just tried that, and now we're back to can't change/establish root
binding of *cljs-repl-env* with set....

**Comment by j-mckitrick** [comment]
@cemerick @tomjakubowski I think I found the issue... though weasel is fine with the latest stable clojurescript, it looks like piggieback requires bleeding edge.  Hopefully that solves the issue.

**Comment by tomjakubowski** [comment]
Glad to hear it!
