### ISSUE TITLE
Network Weasel Repl?

### ISSUE THREAD

**Issue by tillda** [tomjakubowski/weasel#59]
Sorry if my understanding is wrong, but is it possible to run Weasel in such a way that it listens on some port (as nREPL does) and does not occupy the stdin? I like to have only one clojure app (repl) session runnging with all the related processes like Figwheel in the background and using remote repl (in IntelliJ IDEA+Cursive) to connect to an environment. This also doesn't require to start brepl manually every time.

**Comment by tomjakubowski** [comment]
I'm not quite sure what you're asking, sorry. You might be able to configure Leiningen to launch Piggieback + Weasel when nREPL starts (see https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L335). Then all of that project's REPLs would be ClojureScript though...

**Comment by tomjakubowski** [comment]
I think this is actually a piggieback or leiningen question... try running `lein repl :headless`, optionally backgrounding it. When you connect to the Leiningen nREPL (using `lein repl :connect` or from Cursive), start the Weasel REPL in the usual way.

I'm closing as I don't think this is a Weasel issue (I don't think Weasel is even aware of stdin). Please don't hesitate to comment if you have further questions, or for better turnaround ask in the #clojure or #clojurescript IRC channels.
